version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    working_dir: /app
    ports:
      - "8080:8080"
    command: ["./server"]
    depends_on:
      - db
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80" # external:container
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stocktracker
      MYSQL_USER: stockuser
      MYSQL_PASSWORD: stockpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
