version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock-backend
    ports:
      - "80808:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stock-frontend
    ports:
      - "33000:80"
    restart: unless-stopped

networks:
  stocknet:
    driver: bridge

