version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - PORT=8080
    networks:
      - stocknet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stock-frontend
    ports:
      - "3000:80"
    networks:
      - stocknet
    depends_on:
      - backend

networks:
  stocknet:
    driver: bridge

